apiVersion: apps/v1
kind: Deployment

metadata:
  name: smaitic-api

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: smaitic-api

  template:
    metadata:
      labels:
        app: smaitic-api

    spec:
      containers:
        - name: smaitic-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: api-web
              containerPort: {{ .Values.service.port }}

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
{{ toYaml .Values.resources | indent 12 }}